name: .NET Test
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-latest
    env:
      SOLUTION_FILE: LibDbHelper.sln
      TEST_DLL: LibDbHelper.Test\bin\Debug\net48\LibDbHelper.Test.dll
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2
    - name: Restore
      run: msbuild /t:Restore $env:SOLUTION_FILE
    - name: Build
      run: msbuild $env:SOLUTION_FILE
    - name: Setup VSTest
      uses: darenm/Setup-VSTest@v1.3
    - name: Test
      run: vstest.console.exe $env:TEST_DLL
